title: USFSI TS Just the docs template 
description: GitHub Pages for US FSI TS App Innovation team Demos
remote_theme: just-the-docs/just-the-docs@v0.6.2

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts_level: loud # or quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red